# Generated by Django 5.0.6 on 2024-05-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pravesh', '0002_customer_customerdocument_documentset_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='last_name',
        ),
    ]
