# Generated by Django 5.0.6 on 2024-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravesh', '0004_customer_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdocument',
            old_name='file',
            new_name='file_back',
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='file_front',
            field=models.FileField(default=23, upload_to='customer_documents/'),
            preserve_default=False,
        ),
    ]
