# Generated by Django 5.0.6 on 2024-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravesh', '0005_rename_file_customerdocument_file_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'last_name', 'document_number')},
        ),
    ]
